version: '3.9'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ac_push_notifications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p7HWd2DsbL
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  push-notifications-api:
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: p7HWd2DsbL
      DATABASE_NAME: ac_push_notifications
      DATABASE_URL: postgresql://postgres:p7HWd2DsbL@postgres:5432/ac_push_notifications
    ports:
      - '3000:3000'
    command: sh -c "npm run db:migrate && node dist/server.js"

volumes:
  postgres_data:

